org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.21.11
minecraft_version_range=[1.21.1,1.22)
fabric_minecraft_version_range=>=1.21.1 <1.21.12

fabric_loader_version=0.18.4
yarn_mappings=1.21.11+build.1

forge_version=61.1.1
forge_version_range=[61,)
forge_loader_version_range=[61,)

neoforge_version=21.11.45
neoforge_version_range=[21.11,)
neoforge_loader_version_range=[1,)

mod_id=boatstepup
mod_name=Boat Step Up
mod_license=All Rights Reserved
mod_version=1.0.6
mod_group_id=com.aurum.boatstepup
mod_authors=aurum
mod_description=Allows boats to step up one-block height changes.
